### ISSUE TITLE
Build multi-arch

### ISSUE THREAD

**Issue by 6543** [ViViDboarder/drone-webdav#15]
at the moment only for `linux/amd64` it is build ...

with `alpine:edge` as base image we could support:
linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/riscv64, linux/s390x

example: [`codeberg.org/6543/hello:latest`](https://codeberg.org/6543/-/packages/container/hello/latest) ( [Dockerfile](https://codeberg.org/6543/docker-images/src/branch/main/Dockerfile.hello), [pipeline](https://codeberg.org/6543/docker-images/src/branch/main/.woodpecker/hello.yml) )

**Comment by ViViDboarder** [comment]
Yea, ironically, I don't have this image being built or pushed using Drone and it was built via Docker Hub, but that is no longer an option. This could also be done via GitHub Actions fairly easily. I'll take a look.

**Comment by ViViDboarder** [comment]
Done. Now GHA is building and pushing all supported Alpine archs for the latest release.
